# FUNDING.yml
# GitHub Sponsors configuration for SciOS-NG

github: SciOS-NG
patreon: null
open_collective: null
ko_fi: null
liberapay: null
custom: 
  - "mailto:hbdatahoang@gmail.com"
  - "https://vietqr.net/93299463333"   # QR Vietcombank nội địa
