# provider.py

# ==============================================================================
# SciOS Runtime Observability
# Trace Provider
# ==============================================================================

from __future__ import annotations

# ==============================================================================
# Part 1. Imports
# ==============================================================================

import copy
import time
import uuid

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import (
    Any,
    Iterable,
    Mapping,
    Optional,
)


# ------------------------------------------------------------------------------
# Tracing modules
# ------------------------------------------------------------------------------

from .trace import Trace
from .span import Span
from .context import TraceContext
from .manager import TraceManager
from .sampler import TraceSampler
from .processor import TraceProcessor
from .exporter import Exporter


# ==============================================================================
# Part 2. Public API
# ==============================================================================

__all__ = [
    "TraceProvider",
    "ProviderType",
    "ProviderState",
    "ProviderCapability",
    "ProviderStatistics",
    "ProviderReport",
]


# ==============================================================================
# Part 3. Enums & Types
# ==============================================================================


class ProviderType(Enum):
    """
    Type of tracing provider.
    """

    DEFAULT = auto()
    RUNTIME = auto()
    CUSTOM = auto()


class ProviderState(Enum):
    """
    Runtime state of a TraceProvider.
    """

    CREATED = auto()
    STARTING = auto()
    RUNNING = auto()
    STOPPING = auto()
    STOPPED = auto()
    ERROR = auto()
    CLOSED = auto()


class ProviderCapability(Enum):
    """
    Capabilities exposed by a TraceProvider.
    """

    TRACE = auto()
    SPAN = auto()
    CONTEXT = auto()
    SAMPLING = auto()
    PROCESSING = auto()
    EXPORTING = auto()
    SNAPSHOT = auto()
    VALIDATION = auto()


# ==============================================================================
# Part 4. Dataclasses
# ==============================================================================


@dataclass
class ProviderStatistics:
    """
    Runtime statistics for a TraceProvider.
    """

    trace_count: int = 0
    span_count: int = 0
    active_span_count: int = 0
    exported_count: int = 0
    error_count: int = 0

    started_count: int = 0
    stopped_count: int = 0

    created_at: float = field(
        default_factory=time.time,
    )

    updated_at: float = field(
        default_factory=time.time,
    )

    def touch(self) -> None:
        """
        Update the statistics timestamp.
        """

        self.updated_at = time.time()


@dataclass
class ProviderReport:
    """
    Diagnostic report generated by a TraceProvider.
    """

    name: str
    service_name: str

    provider_type: ProviderType
    state: ProviderState

    enabled: bool
    active: bool
    ready: bool

    capabilities: tuple[
        ProviderCapability,
        ...
    ]

    statistics: ProviderStatistics

    trace_id: Optional[str] = None
    span_id: Optional[str] = None

    metadata: dict[str, Any] = field(
        default_factory=dict,
    )

    timestamp: float = field(
        default_factory=time.time,
    )

# ==============================================================================
# Part 5. TraceProvider
# ==============================================================================

class TraceProvider:
    """
    High-level tracing provider.

    TraceProvider owns the high-level provider lifecycle and delegates
    trace/span operations to TraceManager and the optional tracing
    components.
    """

    # --------------------------------------------------------------------------
    # Constructor
    # --------------------------------------------------------------------------

    def __init__(
        self,
        name: str = "provider",
        service_name: str = "scios",
        enabled: bool = True,
        manager: Optional[TraceManager] = None,
        sampler: Optional[TraceSampler] = None,
        processor: Optional[TraceProcessor] = None,
        exporters: Optional[Iterable[Exporter]] = None,
    ) -> None:
        """
        Initialize a TraceProvider.
        """

        # ------------------------------------------------------------------
        # Identity
        # ------------------------------------------------------------------

        self._name = str(name)
        self._service_name = str(service_name)
        self._enabled = bool(enabled)

        # ------------------------------------------------------------------
        # Components
        # ------------------------------------------------------------------

        self._sampler = sampler
        self._processor = processor
        self._exporters = (
            list(exporters)
            if exporters is not None
            else []
        )

        # ------------------------------------------------------------------
        # Manager
        # ------------------------------------------------------------------

        if manager is not None:
            self._manager = manager
        else:
            self._manager = TraceManager(
                name=self._name,
                service_name=self._service_name,
                enabled=self._enabled,
                sampler=self._sampler,
                processor=self._processor,
                exporters=self._exporters,
            )

        # ------------------------------------------------------------------
        # Synchronize components from manager
        # ------------------------------------------------------------------

        if self._sampler is None:
            manager_sampler = getattr(
                self._manager,
                "sampler",
                None,
            )

            if manager_sampler is not None:
                self._sampler = manager_sampler

        if self._processor is None:
            manager_processor = getattr(
                self._manager,
                "processor",
                None,
            )

            if manager_processor is not None:
                self._processor = manager_processor

        if not self._exporters:
            manager_exporters = getattr(
                self._manager,
                "exporters",
                None,
            )

            if manager_exporters is not None:
                self._exporters = list(manager_exporters)

        # ------------------------------------------------------------------
        # Runtime state
        # ------------------------------------------------------------------

        self._context: Optional[TraceContext] = None
        self._trace: Optional[Trace] = None
        self._current_span: Optional[Span] = None

        # ------------------------------------------------------------------
        # Metadata
        # ------------------------------------------------------------------

        self._metadata: dict[str, Any] = {}

        # ------------------------------------------------------------------
        # Provider state
        # ------------------------------------------------------------------

        self._state = ProviderState.CREATED

        # ------------------------------------------------------------------
        # Statistics
        # ------------------------------------------------------------------

        self._statistics = ProviderStatistics()

        # ------------------------------------------------------------------
        # Capabilities
        # ------------------------------------------------------------------

        self._capabilities: set[ProviderCapability] = set()

        self._register_capability(
            "TRACING",
            self._manager is not None,
        )

        self._register_capability(
            "SAMPLING",
            self._sampler is not None,
        )

        self._register_capability(
            "PROCESSING",
            self._processor is not None,
        )

        self._register_capability(
            "EXPORTING",
            bool(self._exporters),
        )

        self._register_capability(
            "ENABLED",
            self._enabled,
        )

        # ------------------------------------------------------------------
        # Initial state
        # ------------------------------------------------------------------

        if not self._enabled:
            self._state = ProviderState.CREATED

    # --------------------------------------------------------------------------
    # Internal capability registration
    # --------------------------------------------------------------------------

    def _register_capability(
        self,
        name: str,
        available: bool = True,
    ) -> None:
        """
        Register a capability if the current ProviderCapability enum
        actually defines it.

        This keeps TraceProvider compatible with the frozen capability
        enum without inventing enum members.
        """

        if not available:
            return

        capability = getattr(
            ProviderCapability,
            name,
            None,
        )

        if capability is not None:
            self._capabilities.add(capability)


# ==========================================================================
# Part 6. Core Properties
# ==========================================================================

    @property
    def name(self) -> str:
        return self._name


    @property
    def service_name(self) -> str:
        return self._service_name


    @property
    def enabled(self) -> bool:
        return self._enabled


    @property
    def state(self) -> ProviderState:
        return self._state


    @property
    def ready(self) -> bool:
        return self._state in (
            ProviderState.CREATED,
            ProviderState.RUNNING,
        )


    @property
    def active(self) -> bool:
        return self._state == ProviderState.RUNNING


    @property
    def manager(self) -> TraceManager:
        return self._manager


    @property
    def trace(self) -> Optional[Trace]:
        return self._trace


    @property
    def current_span(self) -> Optional[Span]:
        """
        Return the currently active span.

        The provider-level cache is authoritative for the high-level API.
        Fall back to the manager when available so the property remains
        synchronized with TraceManager.
        """
        if self._current_span is not None:
            return self._current_span

        manager = self._manager

        current = getattr(manager, "current_span", None)

        if callable(current):
            try:
                current = current()
            except TypeError:
                current = None

        return current


    def context(self) -> TraceContext:
        """Return the current tracing context."""

        context = self._manager.context

        if context is None:
            context = TraceContext()
            self._manager._context = context

        return context


    @property
    def metadata(self) -> dict[str, Any]:
        return dict(self._metadata)


    @property
    def capabilities(self) -> set[ProviderCapability]:
        return set(getattr(self, "_capabilities", set()))


# ==========================================================================
# Part 7. Provider Lifecycle
# ==========================================================================

    def start(self) -> "TraceProvider":
        """Start the tracing provider."""

        if not self._enabled:
            disabled_state = getattr(
                ProviderState,
                "DISABLED",
                None,
            )

            if disabled_state is not None:
                self._state = disabled_state
            else:
                self._state = ProviderState.CREATED

            return self

        self._state = ProviderState.RUNNING
        return self


    def stop(self) -> "TraceProvider":
        """Stop the tracing provider."""

        if self._trace is not None:
            self.finish_trace()

        stopped_state = getattr(
            ProviderState,
            "STOPPED",
            None,
        )

        if stopped_state is not None:
            self._state = stopped_state
        else:
            self._state = ProviderState.CREATED

        self._current_span = None
        self._context = self._manager.current_context()

        return self


    def reset(self) -> "TraceProvider":
        """Reset provider and manager runtime state."""

        reset = getattr(
            self._manager,
            "reset",
            None,
        )

        if callable(reset):
            reset()

        self._context = None
        self._trace = None
        self._current_span = None
        self._metadata.clear()

        self._state = (
            ProviderState.CREATED
            if self._enabled
            else getattr(
                ProviderState,
                "DISABLED",
                ProviderState.CREATED,
            )
        )

        return self


    def clear(self) -> "TraceProvider":
        """Clear active tracing state without changing lifecycle state."""

        clear = getattr(
            self._manager,
            "clear",
            None,
        )

        if callable(clear):
            clear()

        self._context = None
        self._trace = None
        self._current_span = None
        self._metadata.clear()

        return self


    def close(self) -> "TraceProvider":
        """Flush and stop the provider."""

        self.flush()
        self.stop()

        return self


# ==========================================================================
# Part 8. Trace Delegation
# ==========================================================================

    def start_trace(
        self,
        name: Optional[str] = None,
        *,
        metadata: Optional[Mapping[str, Any]] = None,
        **attributes: Any,
    ) -> Optional[Trace]:
        """Start a trace through TraceManager."""

        if not self._enabled:
            return None

        if not self.active:
            self.start()

        trace = self._manager.start_trace(
            name,
            metadata=metadata,
            **attributes,
        )

        self._trace = trace

        # Synchronize context.
        current_context = getattr(
            self._manager,
            "current_context",
            None,
        )

        if callable(current_context):
            try:
                current_context = current_context()
            except TypeError:
                current_context = None

        self._context = current_context

        # Synchronize current span.
        current_span = getattr(
            self._manager,
            "current_span",
            None,
        )

        if callable(current_span):
            try:
                current_span = current_span()
            except TypeError:
                current_span = None

        self._current_span = current_span

        if trace is not None:
            self._statistics.trace_count += 1

        return trace

    def finish_trace(self) -> Optional[Trace]:
        """Finish the active trace."""

        trace = self._manager.finish_trace()

        self._trace = trace
        self._current_span = None

        current_context = getattr(
            self._manager,
            "current_context",
            None,
        )

        if callable(current_context):
            self._context = current_context()
        else:
            self._context = None

        return trace


    def cancel_trace(self) -> Optional[Trace]:
        """Cancel the active trace."""

        trace = self._manager.cancel_trace()

        self._trace = trace
        self._current_span = None

        current_context = getattr(
            self._manager,
            "current_context",
            None,
        )

        if callable(current_context):
            self._context = current_context()
        else:
            self._context = None

        return trace


    def current_trace(self) -> Optional[Trace]:
        """Return the current trace."""

        trace = getattr(
            self._manager,
            "trace",
            None,
        )

        if callable(trace):
            trace = trace()

        if trace is not None:
            self._trace = trace

        return self._trace

# ==========================================================================
# Part 9. Span Delegation
# ==========================================================================

    def start_span(
        self,
        name: Optional[str] = None,
        *,
        parent: Optional[Span] = None,
        attributes: Optional[Mapping[str, Any]] = None,
        **kwargs: Any,
    ) -> Optional[Span]:
        """Start a span through TraceManager."""

        if not self._enabled:
            return None

        if not self.active:
            self.start()

        span_attributes = dict(attributes or {})
        span_attributes.update(kwargs)

        manager_kwargs: dict[str, Any] = {}

        if parent is not None:
            manager_kwargs["parent"] = parent

        span = self._manager.start_span(
            name,
            metadata=span_attributes,
            **manager_kwargs,
        )

        return span


    def finish_span(self) -> Optional[Span]:
        """Finish the current span."""

        span = self._manager.finish_span()

        self._current_span = None
        self._context = self._manager.current_context()

        return span


    def cancel_span(self) -> Optional[Span]:
        """Cancel the current span."""

        span = self._manager.cancel_span()

        self._current_span = None
        self._context = self._manager.current_context()

        return span


    def enter_span(
        self,
        name: Optional[str] = None,
        *,
        parent: Optional[Span] = None,
        attributes: Optional[Mapping[str, Any]] = None,
        **kwargs: Any,
    ) -> Optional[Span]:
        """Start and register a span for context-managed usage."""

        return self.start_span(
            name,
            parent=parent,
            attributes=attributes,
            **kwargs,
        )


    def exit_span(self) -> Optional[Span]:
        """Finish the current span and return it."""

        if not self._enabled:
            return None

        span = self.current_span

        if span is None:
            return None

        result = self._manager.finish_span()

        return result if result is not None else span

    # ==========================================================================
    # Part 10. Context Management
    # ==========================================================================

    def current_context(self) -> TraceContext:
        """Return the current tracing context."""

        return self.context()


    def set_context(
        self,
        context: Optional[TraceContext],
    ) -> "TraceProvider":
        """Set the current tracing context."""

        if context is None:
            context = TraceContext()

        self._manager._context = context

        return self


    def update_context(
        self,
        **values: Any,
    ) -> "TraceProvider":

        method = getattr(
            self._manager,
            "update_context",
            None,
        )

        if callable(method):
            method(**values)

        self._context = self.current_context()

        return self


    def clear_context(self) -> "TraceProvider":
        method = getattr(
            self._manager,
            "clear_context",
            None,
        )

        if callable(method):
            method()

        self._context = None

        return self


    # ==========================================================================
    # Part 11. Metadata & Attributes
    # ==========================================================================

    def set_metadata(
        self,
        key: str,
        value: Any,
    ) -> "TraceProvider":

        self._metadata[key] = value

        return self


    def update_metadata(
        self,
        **values: Any,
    ) -> "TraceProvider":

        self._metadata.update(values)

        return self


    def get_metadata(
        self,
        key: Optional[str] = None,
        default: Any = None,
    ) -> Any:

        if key is None:
            return dict(self._metadata)

        return self._metadata.get(
            key,
            default,
        )


    def set_attribute(
        self,
        key: str,
        value: Any,
    ) -> "TraceProvider":

        span = self.current_span

        if span is not None:
            setter = getattr(
                span,
                "set_attribute",
                None,
            )

            if callable(setter):
                setter(
                    key,
                    value,
                )
                return self

        self._metadata[key] = value

        return self


    def add_event(
        self,
        name: str,
        **attributes: Any,
    ) -> "TraceProvider":

        span = self.current_span

        if span is not None:
            add_event = getattr(
                span,
                "add_event",
                None,
            )

            if callable(add_event):
                add_event(
                    name,
                    **attributes,
                )
                return self

        events = self._metadata.setdefault(
            "events",
            [],
        )

        events.append(
            {
                "name": name,
                "attributes": dict(attributes),
            },
        )

        return self


    # ==========================================================================
    # Part 12. Processing
    # ==========================================================================

    def process_span(
        self,
        span: Optional[Span],
    ) -> Optional[Span]:

        if span is None:
            return None

        processor = self._processor

        if processor is None:
            return span

        process = getattr(
            processor,
            "process",
            None,
        )

        if callable(process):
            result = process(span)
            return span if result is None else result

        return span


    def process_trace(
        self,
        trace: Optional[Trace],
    ) -> Optional[Trace]:

        if trace is None:
            return None

        processor = self._processor

        if processor is None:
            return trace

        process = getattr(
            processor,
            "process",
            None,
        )

        if callable(process):
            result = process(trace)
            return trace if result is None else result

        return trace


    def process(
        self,
        item: Any = None,
    ) -> Any:

        if item is None:
            item = self.current_span

            if item is None:
                item = self.current_trace()

        if item is None:
            return self

        if isinstance(item, Span):
            return self.process_span(item)

        if isinstance(item, Trace):
            return self.process_trace(item)

        return item


    # ==========================================================================
    # Part 12A. Snapshot & Restore
    # ==========================================================================

    def snapshot(self) -> Any:
        """Create a provider/manager snapshot."""

        manager = self._manager

        method = getattr(
            manager,
            "snapshot",
            None,
        )

        if callable(method):
            return method()

        return {
            "name": self._name,
            "service_name": self._service_name,
            "enabled": self._enabled,
            "state": self._state,
            "active": self.active,
            "trace": self._trace,
            "context": self._context,
            "current_span": self._current_span,
            "metadata": dict(self._metadata),
        }


    def restore(
        self,
        snapshot: Any,
    ) -> "TraceProvider":
        """Restore provider/manager state from a snapshot."""

        manager = self._manager

        method = getattr(
            manager,
            "restore",
            None,
        )

        if callable(method):
            method(snapshot)

        if isinstance(snapshot, Mapping):
            if "trace" in snapshot:
                self._trace = snapshot["trace"]

            if "context" in snapshot:
                self._context = snapshot["context"]

            if "current_span" in snapshot:
                self._current_span = snapshot["current_span"]

            if "metadata" in snapshot:
                self._metadata = dict(
                    snapshot["metadata"],
                )

        return self

    # ==========================================================================
    # Part 13. Sampling
    # ==========================================================================

    def should_sample(
        self,
        trace: Optional[Trace] = None,
    ) -> bool:

        sampler = self._sampler

        if sampler is None:
            return True

        method = getattr(
            sampler,
            "should_sample",
            None,
        )

        if callable(method):
            try:
                return bool(
                    method(trace),
                )
            except TypeError:
                return bool(
                    method(),
                )

        return True


    def sampling_decision(
        self,
        trace: Optional[Trace] = None,
    ) -> Any:

        sampler = self._sampler

        if sampler is None:
            return True

        method = getattr(
            sampler,
            "sampling_decision",
            None,
        )

        if callable(method):
            try:
                return method(trace)
            except TypeError:
                return method()

        return self.should_sample(trace)


# ==========================================================================
# Part 14. Export
# ==========================================================================

    def export_span(
        self,
        span: Optional[Span],
    ) -> Any:
        """Export a span."""

        if span is None:
            return None

        result = span

        for exporter in getattr(
            self,
            "_exporters",
            [],
        ):
            if exporter is None:
                continue

            method = getattr(
                exporter,
                "export_span",
                None,
            )

            if callable(method):
                exported = method(span)

                if exported is not None:
                    result = exported

        self._statistics.exported_count += 1

        return result


    def export_trace(
        self,
        trace: Optional[Trace],
    ) -> Any:
        """Export a trace."""

        if trace is None:
            return None

        result = trace

        for exporter in getattr(
            self,
            "_exporters",
            [],
        ):
            if exporter is None:
                continue

            method = getattr(
                exporter,
                "export_trace",
                None,
            )

            if callable(method):
                exported = method(trace)

                if exported is not None:
                    result = exported

        self._statistics.exported_count += 1

        return result


    def export(self) -> Any:
        """Export current provider state."""

        if self._trace is not None:
            return self.export_trace(self._trace)

        if self._current_span is not None:
            return self.export_span(self._current_span)

        return {
            "provider": self._name,
            "service_name": self._service_name,
            "trace": None,
            "span": None,
        }


    def flush(self) -> "TraceProvider":
        """Flush configured exporters."""

        for exporter in getattr(
            self,
            "_exporters",
            [],
        ):
            if exporter is None:
                continue

            method = getattr(
                exporter,
                "flush",
                None,
            )

            if callable(method):
                method()

        return self

# ==========================================================================
# Part 15. Validation & Health
# ==========================================================================

    def validate(self) -> bool:
        """Validate provider state and core dependencies."""

        return self.validate_state()


    def validate_state(self) -> bool:
        """Validate the current provider state."""

        if self._manager is None:
            return False

        if not self._enabled:
            return False

        # Do not reference ProviderState.DISABLED here.
        # The frozen enum does not define that member.
        valid_states = {
            ProviderState.CREATED,
            ProviderState.RUNNING,
            ProviderState.STOPPED,
        }

        if self._state not in valid_states:
            return False

        return True


    def validate_trace(
        self,
        trace: Optional[Trace],
    ) -> bool:
        """Validate a trace instance."""

        if trace is None:
            return False

        validator = getattr(
            self._manager,
            "validate_trace",
            None,
        )

        if callable(validator):
            try:
                return bool(validator(trace))
            except TypeError:
                pass

        return isinstance(trace, Trace)


    def validate_span(
        self,
        span: Optional[Span],
    ) -> bool:
        """Validate a span instance."""

        if span is None:
            return False

        validator = getattr(
            self._manager,
            "validate_span",
            None,
        )

        if callable(validator):
            try:
                return bool(validator(span))
            except TypeError:
                pass

        return isinstance(span, Span)


    def health(self) -> bool:
        """Return whether the provider is operational."""

        return bool(
            self._enabled
            and self.ready
            and self.validate_state()
        )


# ==========================================================================
# Part 16. Copy / Clone
# ==========================================================================

    def copy(self) -> "TraceProvider":
        """Create a safe provider copy."""

        provider = TraceProvider(
            name=self._name,
            service_name=self._service_name,
            enabled=self._enabled,
            sampler=self._sampler,
            processor=self._processor,
            exporters=list(
                getattr(
                    self,
                    "_exporters",
                    [],
                )
            ),
        )

        provider._metadata = dict(self._metadata)
        provider._state = self._state
        provider._capabilities = set(self._capabilities)

        return provider


    def clone(self) -> "TraceProvider":
        """Create a new provider with equivalent configuration."""

        return self.copy()

    # ==========================================================================
    # Part 17. Statistics
    # ==========================================================================

    @property
    def trace_count(self) -> int:
        return self._statistics.trace_count


    @property
    def span_count(self) -> int:
        return self._statistics.span_count


    @property
    def active_span_count(self) -> int:
        manager = self._manager

        value = getattr(
            manager,
            "span_depth",
            None,
        )

        if value is not None:
            return int(value)

        return 1 if self.current_span is not None else 0


    @property
    def exported_count(self) -> int:
        return self._statistics.exported_count


    @property
    def error_count(self) -> int:
        return self._statistics.error_count


    # ==========================================================================
    # Part 18. Diagnostics
    # ==========================================================================

    def health(self) -> bool:
        return (
            self._enabled
            and self.ready
            and self.validate_state()
        )


    def diagnostics(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "service_name": self.service_name,
            "enabled": self.enabled,
            "state": self.state,
            "ready": self.ready,
            "active": self.active,
            "trace_count": self.trace_count,
            "span_count": self.span_count,
            "active_span_count": self.active_span_count,
            "exported_count": self.exported_count,
            "error_count": self.error_count,
        }


    def summary(self) -> dict[str, Any]:
        return self.diagnostics()


    # ==========================================================================
    # Part 19. Representation
    # ==========================================================================

    def __repr__(self) -> str:
        return (
            "TraceProvider("
            f"name={self.name!r}, "
            f"service_name={self.service_name!r}, "
            f"enabled={self.enabled!r}, "
            f"state={self.state!r}, "
            f"active={self.active!r}"
            ")"
        )


    def __str__(self) -> str:
        return self.__repr__()


    def _ensure_context(self) -> TraceContext:
        context = self._manager.context

        if context is None:
            context = TraceContext()
            self._manager._context = context

        return context
# ==========================================================================
# Part 20. End
# ==========================================================================

__all__ = [
    "TraceProvider",
    "ProviderType",
    "ProviderState",
    "ProviderCapability",
    "ProviderStatistics",
    "ProviderReport",
]
